#!/usr/bin/env bash

BORDER="#bd93f9"
SEPARATOR="#1F1F1F"
FOREGROUND="#f8f8f2"
BACKGROUND="#282a36"
BACKGROUND_ALT="#44475a"
HIGHLIGHT_BACKGROUND="#bd93f9"
HIGHLIGHT_FOREGROUND="#f8f8f2"

BLACK="#000000"
WHITE="#ffffff"
RED="#e53935"
GREEN="#43a047"
YELLOW="#fdd835"
BLUE="#1e88e5"
MAGENTA="#00897b"
CYAN="#00acc1"
PINK="d81b60"
PURPLE="#8e24aa"
INDIGO="#3949ab"
TEAL="#00897b"
LIME="#c0ca33"
AMBER="#ffb300"
ORANGE="#fb8c00"
BROWN="#6d4c41"
GREY="#757575"
BLUE_GREY="#546e7a"
DEEP_PURPLE="#5e35b1"
DEEP_ORANGE="#f4511e"
LIGHT_BLUE="#039be5"
LIGHT_GREEN="#7cb342"

shopt -s nullglob
set -e
set -o pipefail

readonly PROGNAME="$(basename "${0}")"
readonly PROGDIR="$( cd "$( dirname "$( readlink -f "${BASH_SOURCE[0]}" )" )" && pwd )"

# shellcheck disable=SC1090
# shellcheck disable=SC1091
if [ -s "${PROGDIR}/lib/functions" ]; then
  source "${PROGDIR}/lib/functions"
else
  source '/usr/lib/splatmoji/functions'
fi

main() {
  parse_args "$@" || \
    if [[ $? -eq 255 ]]; then
      # Printing help and listing langs both return 255 as a signal to exit
      # here with success
      exit 0
    else
      exit 1
    fi

  # Get configuation
  local conffile
  conffile="$(get_config_file)"
  declare -A config
  get_config "${conffile}" config

  # Get list of data files
  # shellcheck disable=SC2034
  local datafiles_list=()
  collect_data_files "${DISABLE_EMOJI_DB}" "${DISABLE_EMOTICON_DB}" LANGUAGES CLI_DATA_FILES datafiles_list

  # User selection
  local selection
  selection="$(get_user_selection SKIN_TONES_EXCLUDE datafiles_list "${config['rofi_command']}")"
  # Remove prepended unicode left-to-right mark if present
  selection=${selection#$'\u200e'}
  if [ -n "${ESCAPE}" ]; then
    selection=$(escape_selection "${selection}" "${ESCAPE}")
  fi

  if [ "${SUBCOMMAND}" == 'type' ]; then
    output_typed "${config[xdotool_command]}" "${selection}"
  else
    output_copied "${config[xsel_command]}" "${selection}"
  fi
}

main "$@"
